name: Python CI
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: [ '5432:5432' ]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install uv
          make install
      - name: Install venv
        run: |
          uv python install 3.11
          uv venv --python 3.11.0
      - name: Run migrations
        run: |
          python manage.py migrate
      - name: Run linter
        run: |
          make check
      - name: Test coverage
        run: |
          make coverage

